### ISSUE TITLE
Debug why 000webhost works at times, but not always

### ISSUE THREAD

**Issue by andreherberth** [andreherberth/pockethold#15]
#13 #11 #12 #14 - Will all help I hope

**Comment by Felli** [comment]
Would seem that Hostinger also has this issue.

**Comment by andreherberth** [comment]
Which one? hostinger.co.uk, or .com? And on one of their paid plans? 

In any case, I am refactoring the code to use "create-project --no-install" and manually require dependencies one at a time. This should solve the problems. Alternatively, download the flarum/flarum github release, and then require vendors one by one.
