### ISSUE TITLE
Optional Upgrade Feature

### ISSUE THREAD

**Issue by Ralkage** [andreherberth/pockethold#25]
Eventually, it would be awesome if this installer could handle upgrading Flarum to the latest build.

**Requirements:**
- The script searches for any currently installed Flarum versions based on ./vendor/composer/installed,json (or any other easier means of identification).
- Provide an upgrade button upon which upgrades Flarum to the current version.
- Display any errors to why the current installation cannot be upgraded.

If not, I would recommend an **upgrade.php** option that handles upgrades. 

That is, until, Flagrow introduces that magical "upgrade" option down the line <3 @luceos

**Comment by luceos** [comment]
I think Bazaar could also do that.. We haven't tried yet though :grin:

**Comment by andreherberth** [comment]
As I mentioned in the forum thread, I am somewhat unsure if I should. 
How to handle outdated extensions for instance? 

I could for instance have a disclaimer agreement checkbox thingy to make users aware of the risks and so on, but I am afraid people trust things to much and barges away without backup up before hand. 

ref: https://discuss.flarum.org/d/5731-pockethold-a-web-based-installer/55

What do you guys think?

**Comment by andreherberth** [comment]
It seems Bazaar might get an upgrade function in the near feature TM see https://github.com/flagrow/bazaar/issues/80

If this happens, I might not spend time making an update version of pockethold.
