### ISSUE TITLE
"Style the Installer" and upgrade to Bootstrap 4?

### ISSUE THREAD

**Issue by KevSlashNull** [andreherberth/pockethold#26]
Hey,

I first wanted to create a Flarum web installer on my own, but then I discovered this **pockethold**.

[This link](https://streamable.com/ze9cq) takes you to a video of my installer. I only coded two or three hours on it and it had some major issues like not beeing able to reload the tab or continue from a second device like pockethold is able to.

I still like the vertical timeline or at least some more visual feedback from what is happening. So I forked the repo and made the following changes.

- Update to Bootstrap 4.0.0-beta
- Add font-awesome (4.7.0)
- Replace `h2` and `span` to `button` with `disabled` attribute and a spinning font-awesome gear.
- Add a progress bar for the Flarum installation
- Add a `<title>`

And that looks like [this](https://streamable.com/qdxih). Code [here](https://github.com/KevSlashNull/pockethold).

What I want to say with this issue is that Pockethold, even in alpha, could get some love to it's style. Not exactly what I programmed, but not "only" text.

Aaand maybe upgrade to Bootstrap 4 even if it's in beta, it looks really cool to me compared with Boostrap 3.

KevSlashNull. ^-^

**Comment by andreherberth** [comment]
Hi, thank you for showing interest in contributing to pockethold.

Your UI additions is most welcome, so I incite you to do a pull request. 

I am also be interested in your vertical timeline approach. 

If I visit the pockethold installer from another browser, it simply only check with the server what the current install status is, so it would be easy to "rebuild" the timeline based on status gotten from the server. 

In your example, did you have any server side code yet? It would be interesting to see how you did the requirement checks.

**Comment by KevSlashNull** [comment]
Hey,

I've created pull request #27.

Okay, I will try to implement the vertical timeline into pockethold the following days.

I have some server side code, but it's not that well-engineered yet. Just testing for Composer and PHP, I think.

**Comment by andreherberth** [comment]
I have merged your #27 into master.
