### ISSUE TITLE
It doesn't complete

### ISSUE THREAD

**Issue by ghost** [andreherberth/pockethold#29]
The download just sits at 1 of 87 and never moves. Is there something I am doing wrong?

**Comment by andreherberth** [comment]
Hi @ZapTechAdmin 

I am sorry for your problems. 

In your /temp folder, there should be some log files, could you please upload these, and I will take a look.

In the meanwhile, I am attaching a compiled version of flarum with bazaar which should be good to go. just extract it. Please note, the zip file have the content inside a folder. You might have to move the files.
I am on a corporate computer atm, and could not change the zip without damaging the permissions on the files from here. 

[flarumnew.zip](https://github.com/andreherberth/pockethold/files/1430027/flarumnew.zip)

**Comment by ghost** [comment]
Thanks @andreherberth 
I tried downloading composer on my local computer, downloading the files for flarum, and transferring them to my webserver, so I will see if it works. If it doesn't, I will try your version of the flarum. Thanks tons for your help!

**Comment by ghost** [comment]
@andreherberth 
I tried this again via a local install in MAMP and it is now stuck at 1 of 91. BTW I tried your file and it worked for installing, but after the install it told me that there was an error loading the full page..... any help ASAP would be appreciated!

**Comment by synergico** [comment]
Hi @ZapTechAdmin 
I got it to work. Here were the steps (I used shared host with CPanel on Godaddy, PHP 7.1)
say the folder you want to host flarum is Flarum-folder
1. Upload both pockethold and the flarumnew.zip aboved to Flarum-folder. Unzip both. 
2. Moved the content of pockethold to Flarum-folder.
3. Rename the unzip of flarumnew.zip, which is _flarum_ to _flarumtemp_
4. Go to browser and run the installer.php. Note: Step 2: Downloading Flarum will quickly showed complete instead of downloading files 
It should work. :)

**Comment by andreherberth** [comment]
@synergico In that case, you should be able to just move the content of the unziped "flarum" folder to where you want flarum to be installed. No need to run pockethold at all. 

However, it might be running pockethold, and it's composer process, fixes some local issues though. I will have to test it :)

In any case, thanks for posting your solution here.

**Comment by ghost** [comment]
‎Thanks tons! I will try this out today


Sent from my BlackBerry 10 smartphone on the Rogers network.
From: synergico
Sent: Thursday, December 14, 2017 6:32 AM
To: andreherberth/pockethold
Reply To: andreherberth/pockethold
Cc: Joel Bond; Mention
Subject: Re: [andreherberth/pockethold] It doesn't complete (#29)



Hi @ZapTechAdmin<https://github.com/zaptechadmin>
I got it to work. Here were the steps (I used shared host with CPanel on Godaddy, PHP 7.1)
say the folder you want to host flarum is Flarum-folder

  1.  Upload both pockethold and the flarumnew.zip aboved to Flarum-folder. Unzip both.
  2.  Moved the content of pockethold to Flarum-folder.
  3.  Rename the unzip of flarumnew.zip, which is flarum to flarumtemp
  4.  Go to browser and run the installer.php
It should work. :)

**Comment by synergico** [comment]
Hi @andreherberth ,
you are absolutely right, your flarumnew.zip works as a charm. 

This make me wonder: What is the point of having the composer running if the pre-composed .zip file work well? Shouldn't it be more user friendly this way.

I imagine that Flarum will have an update option in admin panel in the future, and there might be no need to use composer for updating?

Thank you for the pockethold. It work flawlessly locally.

**Comment by andreherberth** [comment]
Will hopefully be fixed by #31
