### ISSUE TITLE
Rework for v0.1.0 (Again)

### ISSUE THREAD

**Issue by andreherberth** [andreherberth/pockethold#38]
For Pockethold to be a viable option in the future, and it's added workload, I am moving away from my original goal, which was to provide a singlefile way of installing Flarum via Web-browser. 

Beta 8 version of Pockethold will come bundles with composer 1.7.1 (Latest working with pockethold). 
It will also, if not at first release, have the option to use "cron". These options should in theory increase the chance of Pockethold being able to setup flarum on shared hosts.

**Comment by andreherberth** [comment]
Working 

- [x] Rough rewrite enabling Beta 8 support. Published already
- [x] Split into several files
- [x] Bundle with Composer 1.7.2
- [ ] Add Rough Cron support
- [x] Redesign installer.php UI
- [ ] Cleanup pockethold class

**Comment by luceos** [comment]
The 1GB requirement for Bazaar isn't really necessary to be mentioned (on top of composer) when using Bazaar with cron processing per default; which is my recommendation anyway. I'll most likely add something inside Bazaar to make people more aware of that configuration.

I'm not sure you're able to force that setting from the get-go? It's a settings key you could pre-fill.

Great job moving forward with this 👍

**Comment by andreherberth** [comment]
In theory this should work: 

> if ( $ini_get_option_details['memory_limit']['access'] & INI_USER ) {
            ini_set('memory_limit', '1G');
        } else {
            die("Not enough memory!");
        }

Not sure how much an impact it really does though. It seems to work on my two plesk servers, but then again, these are not really that shared. 

I also got it semi working on hostingers free plan, but it depended on how taxed the server was at the moment, as it seemed to max out the server memory itself, and thus staling. 

It is high time I edit my readme. I might just do that when the "cron" support is added. The new UI will also provide much more information to the user, and it is natural that the last step before cleanup includes information in regards of bazaars cron feature as well :)

**Comment by andreherberth** [comment]
Closed due to project goal change.
