### ISSUE TITLE
Stuck on "Getting Status"

### ISSUE THREAD

**Issue by ghost** [andreherberth/pockethold#41]
Hello there!
Today, I've tried to install Flarum with Pockethold. 
I've created a folder called "flarum" and then I've unzipped Pockethold in the folder.
Then I launched the installer.php
But I'm stuck on "Getting Status" and I can't start the installation
What should I do?
Thanks in advance :)

**Comment by andreherberth** [comment]
Hi. What link did you use for the download?

**Comment by ghost** [comment]
Hi. I've only downloaded Pockethold from GitHub. Then I've followed the instruction here on GitHub (`Usage: Upload installer.php where you want Flarum to be installed. Visit the the default: yoururl.com/installer.php and follow the instructions.)`

P.S: Merry Christmas! :)

**Comment by andreherberth** [comment]
Ah, gotta change that text. Newest version is no longer a singlefile installer. 

Make sure you use this one https://github.com/Pockethold/pockethold/releases/download/v0.1.0-beta.6/v0.1.0-beta.6-pockethold.zip

And upload all content and try again. 

Merry Christmas :)

**Comment by ghost** [comment]
Alright. Thank you very much! :)
