### ISSUE TITLE
Issue intalling bazaar

### ISSUE THREAD

**Issue by aguilaair** [andreherberth/pockethold#46]
Hello,

I am using BlueHost to test out Flarum and after trying to run Pockethold it gets stuck on step 3 with the following message on the log: 

`./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
`

It seems to have frozen eventhough I've given it 2048M in the php.ini.

Any suggestions would be appriciated!

**Comment by piperzeng** [comment]
Hi I encountered the same issue and still stuck there. Do you have any idea now? Thank you!
