### ISSUE TITLE
Installation doesn't progress

### ISSUE THREAD

**Issue by hrishikesh-k** [andreherberth/pockethold#47]
I'm trying this on InfinityFree host. I just wanted to make sure it works with that host before I actually connect my domain and all.

So, this is the URL: http://forum2500.epizy.com/installer.php

It asked me to download the files of Flarum and then, it just shows 'Current Task Log' with no progress (except, it keeps blinking). Is it working, is it not? Can someone tell?

Edit: I have now found that my PHP memory limit is just 158MB and it can't increase.

**Comment by Aerstme** [comment]
Same error here, my php limit memory is unlimited.

**Comment by 4yx** [comment]
Have you applied the fix described on https://github.com/Pockethold/pockethold/issues/45? Sorry for the late reply.

**Comment by hrishikesh-k** [comment]
I did that now, no change. See here: https://www.compuro.ml/flarum/installer.php

**Comment by 4yx** [comment]
So you added a log folder and an ajax.log file and nothing happened?
Can you try setting their permissions to 777 and retry the installation?

**Comment by hrishikesh-k** [comment]
> So you added a log folder and an ajax.log file and nothing happened?
> Can you try setting their permissions to 777 and retry the installation?

Yes. Nothing happened. Logs got written to the file. The permissions are 777.

This is what the logs (ajax.log) show:

Tue Jul 9 14:09:59: Ajax Allowed: status
Tue Jul 9 14:10:00: Ajax Allowed: flarum
Tue Jul 9 14:10:05: Ajax Allowed: status
Tue Jul 9 14:10:10: Ajax Allowed: progress
Tue Jul 9 14:10:11: Ajax Allowed: status
Tue Jul 9 14:10:12: Ajax Allowed: progress
Tue Jul 9 14:10:19: Ajax Allowed: status
Tue Jul 9 14:10:25: Ajax Allowed: status
Tue Jul 9 14:10:27: Ajax Allowed: progress
... same thing is repeated till the end.

**Comment by andreherberth** [comment]
Hi. What version are you using?

There should also be an composer.log file, it should be in the same folder, it would provide some more useful information.

**Comment by hrishikesh-k** [comment]
I downloaded the one from under the assets in the releases here: https://github.com/Pockethold/pockethold/releases some 2 days ago. Didn't really see the version number then but, I had downloaded whichever was the latest (which looking at the dates, it seems it was beta 6).

There's no composer.log, but, there's flarum.log and flarum.start. Both are empty.

**Comment by andreherberth** [comment]
It would then seem, since flarum.log is empty that something is blocking pockethold from proceeding 🤔 do you have access to the error  logs on the server?

**Comment by hrishikesh-k** [comment]
Sadly, I'm using a free host. They recently disabled logs for free
accounts. So, no, I don't have access to logs.

**Comment by imba-tjd** [comment]
You are using `infinityfree.net` which seems to have a 10MB file size limit. I wonder whether this is the problem.

**Comment by hrishikesh-k** [comment]
That's possible. But, nowhere on Pockethold, a file size limit was
mentioned. Is it really the problem?

**Comment by andreherberth** [comment]
I am uncertain to be honest. It downloads archives of each and every depentancy. I have not messured if any of those reach 10mb in size. Alas, if this had been the issue in this case, the flarum.log would have had details.

It's seems more likely that it kills the composer process before it starts output. If this is the case, and if we don't have any logs, I don't think I have the means to troubleshoot this further 😕

**Comment by hrishikesh-k** [comment]
Okay. That's sad to know. But, just to try, I created an account on 000webhost and installed Flarum there. I clicked on download flarum, within a second it switched to download bazaar, and when  clicked on that, within another second it was like, done. But, when I try to visit /index.php now, this is the error page I get:

Warning: require(vendor/autoload.php): failed to open stream: No such file or directory in /storage/ssd2/979/10171979/public_html/forum/index.php on line 12

Warning: require(vendor/autoload.php): failed to open stream: No such file or directory in /storage/ssd2/979/10171979/public_html/forum/index.php on line 12

Fatal error: require(): Failed opening required 'vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /storage/ssd2/979/10171979/public_html/forum/index.php on line 12

**Comment by andreherberth** [comment]
Ok that's just weird, as I have succesfulyl downloaded on 000webhost before. Alas, I have not verified it after beta 8 (or beta 9 for that matter). 

But, since it goes to "bazaar", it means it actually "Finishes" the composer part of the script before moving on. I don't have error checking in place, as that should have in theory been displayed if any in the console emulation on the page.

If you could do me a big favor? Run the script on 000webhost again, but try to backup the log directory before it deletes it, so I can have a look at the flarum.log file :) 

It should provide some pointers on what's going on.

**Comment by hrishikesh-k** [comment]
I'm attaching 2 zips.

logs.zip is the one after it showed Flarum was done and gave me an option to install Bazaar. [logs.zip](https://github.com/Pockethold/pockethold/files/3385540/logs.zip)

logs2.zip is the one after installing Bazaar. [logs2.zip](https://github.com/Pockethold/pockethold/files/3385543/logs2.zip)

And yeah, by the way, even after the second installaition, I'm getting the same errors like I mentioned before. You can check the page here: https://apterous-accumulati.000webhostapp.com/forum2/

**Comment by andreherberth** [comment]
Hi, thanks this helped a great deal. Not sure exactly what causes this to happened selectively on different hosts, but at least I believe I can counter it. Hopefully I can get a new version out in a few days :)

**Comment by hrishikesh-k** [comment]
Great to know that it helped. Good luck with the new version.

**Comment by andreherberth** [comment]
It helped, but I am uncertain now if I can fix it. 

The problem here seems to be that the hosts disables the possibility to set custom environment variables, or limits them to certain variables. Your issue indicates that pockethold is refused to define "COMPOSER_HOME". 

I will investigate more though, might be I can find a workaround.

**Comment by andreherberth** [comment]
Closed due to inactivity. I have yet to find a way to add environment variables.
