### ISSUE TITLE
Flarum requires PHP 7.1 or greater. Your versions is 7.3.2

### ISSUE THREAD

**Issue by JCKodel** [andreherberth/pockethold#48]
![image](https://user-images.githubusercontent.com/379339/61840049-53f56880-ae66-11e9-91b0-fccdf7097bd8.png)

**Comment by andreherberth** [comment]
Hi, thanks for pointing this out. 

Alas, this is from the unstable master, many other things are broken as well until the new things are finished. 

I recommend using the archive inside the latest release instead.
