### ISSUE TITLE
It's stuck here

### ISSUE THREAD

**Issue by ghost** [andreherberth/pockethold#49]
Installing flarum/flarum (v0.1.0-beta.11)
<warning>As there is no 'unzip' command installed zip files are being unpacked using the PHP zip extension.</warning>
<warning>This may cause invalid reports of corrupted archives. Installing 'unzip' may remediate them.</warning>
  - Installing flarum/flarum (v0.1.0-beta.11): Downloading (100%)
Created project in ./pockethold/download
Loading composer repositories with package information
Updating dependencies (including require-dev)

**Comment by ghost** [comment]
![](https://puui.qpic.cn/fans_admin/0/3_1680187318_1579713179462/0)

**Comment by andreherberth** [comment]
@emeomo Could you clean out the folder and run the intaller again. Try to catch the pockethold logs before it deletes the folder? It should provide some clue to why it fails. You could also monitor the error logs, depending on the control panel you use, it should be available as an option.

**Comment by ghost** [comment]
我放弃安装flarum了  我太笨了

**Comment by lem0nb** [comment]
> 
> 
> 我放弃安装flarum了 我太笨了

安装fileinfo拓展
