### ISSUE TITLE
Javascript Error on line 28

### ISSUE THREAD

**Issue by goodmuyis** [andreherberth/pockethold#53]
`$("#progress").html('<pre id=\'consoleoutput\' style=\'white-space: pre-wrap; text-align:left; height: 300px; max-height: 300px; overflow:auto; color:#fff;\'>'data'</pre>');`

Am more comfortable using backtick so I change my code which work but I got error 500 on on first run with logged php error

`2020-02-08 22:36:09.824665 [NOTICE] ...[STDERR] PHP Parse error:  syntax error, unexpected 'return' (T_RETURN) in /home/.../public_html/pockethold/classes/pockethold.class.php on line 242`

an indication of inability to create log file

Does this script depends on composer?

**Comment by andreherberth** [comment]
Was this using the release version?

**Comment by goodmuyis** [comment]
> Was this using the release version?

Yes of this one [here](https://github.com/Pockethold/pockethold/archive/master.zip)

**Comment by andreherberth** [comment]
Ah, alas, that's a snapshot of the current dev version, and is not working at all right now. 
I am in the middle of a rebuild, and are moving from laptop and desktop quite often, and push my code after each session. Not a very good practice I know, but...

Latest release can be found under the releases tab. 
https://github.com/Pockethold/pockethold/releases/tag/v0.1.0-beta.6

But a good catch anyway :D

I will leave the ticket open until I push my next session. :)

**Comment by goodmuyis** [comment]
Am able to install Flarum successfully so am closing this.

Thanks for the help
