### ISSUE TITLE
Bundle Prestissimo to speed up composer (timeout issues)

### ISSUE THREAD

**Issue by KyrneDev** [andreherberth/pockethold#54]
I've seen a lot of people having issues with timeouts due to composer taking a really long time to complete. Would it makes sense to bundle https://github.com/hirak/prestissimo in an attempt to avoid timeout issues?

**Comment by andreherberth** [comment]
Solved by bundling Composer 2 preview build in latest release https://github.com/Pockethold/pockethold/releases/tag/0.1.0
