### ISSUE TITLE
Broken code

### ISSUE THREAD

**Issue by VeeBack** [andreherberth/pockethold#56]
https://github.com/Pockethold/pockethold/blob/8d82b833b9eff68651c48eae718d518f5a717a0c/pockethold/classes/pockethold.class.php#L26
This line causes ```
<br />
<b>Parse error</b>: syntax error, unexpected '$this' (T_VARIABLE), expecting ')' in <b>D:\htdocs\Manhunt\Forum\pockethold\classes\pockethold.class.php</b> on line <b>26</b><br />
```

**Comment by andreherberth** [comment]
Hi, @HVEVB, 

Thanks for reporting the bug. This seems to have arrived in my latest push to the master branch. 
I would generally recommend that the latest release should be use though:
https://github.com/Pockethold/pockethold/releases/tag/0.1.0

I will push a fix for this issue shortly though :)
